[package]
name = "text-formatter-rust"
version = "0.1.0"
authors = ["ikkz <ylei.mk@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]
parallel = [ "wasm-bindgen-rayon"]

[dependencies]
wasm-bindgen = "0.2.84"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
regex = "1.10.2"
lazy_static = "1.4.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
utf8_slice = "1.0.0"
rayon = { version = "1.8.0" }
wasm-bindgen-rayon = { version = "1.1.3", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
